=== MariaInesRibeiro98/GameBus-HealthBehaviorMining/schema/OCEL-mHealth.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "sensorEventTypes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": { "type": "string" },
                    "attributes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": { "type": "string" },
                                "type": { "type": "string" }
                            },
                            "required": ["name", "type"]
                        }
                    }
                },
                "required": ["name", "attributes"]
            }
        },
        "behaviorEventTypes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": { "type": "string" },
                    "attributes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": { "type": "string" },
                                "type": { "type": "string" }
                            },
                            "required": ["name", "type"]
                        }
                    }
                },
                "required": ["name", "attributes"]
            }
        },
        "objectTypes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": { "type": "string" },
                    "attributes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": { "type": "string" },
                                "type": { "type": "string" }
                            },
                            "required": ["name", "type"]
                        }
                    }
                },
                "required": ["name", "attributes"]
            }
        },
        "sensorEvents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": { "type": "string" },
                    "sensorEventType": { "type": "string" },
                    "time": { "type": "string", "format": "date-time" },
                    "sensorEventTypeAttributes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": { "type": "string" },
                                "value": { "type": [ "string", "number" ] }
                            },    
                            "required": ["name", "value"]
                        }
                    },
                    "relationships": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": { "type": "string" },
                                "type": {"type": "string", "enum": ["behaviorEvent", "object"]},
                                "qualifier": { "type": "string" }
                            },
                            "required": ["id", "type", "qualifier"]
                        }
                    }
                },
                "required": ["id", "sensorEventType", "time"]
            }
        },
        "behaviorEvents": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": { "type": "string" },
                    "behaviorEventType": { "type": "string" },
                    "time": { "type": "string", "format": "date-time" },
                    "behaviorEventTypeAttributes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": { "type": "string" },
                                "value": { "type": [ "string", "number" ] }
                            },
                            "required": ["name", "value"]
                        }
                    },
                    "relationships": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": { "type": "string" },
                                "type": { "type": "string", "enum": ["object"]},
                                "qualifier": { "type": "string" }
                            },
                            "required": ["id", "type", "qualifier"]
                        }
                    }
                },
                "required": ["id", "behaviorEventType", "time"]
            }
        },
        "objects": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": { "type": "string" },
                    "type": { "type": "string" },
                    "relationships": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": { "type": "string" },
                                "type": { "type": "string", "enum": ["object", "behaviorEvent"] },
                                "qualifier": { "type": "string" }
                            },
                            "required": ["id", "type", "qualifier"]
                        }
                    },
                    "attributes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": { "type": "string" },
                                "value": { "type": [ "string", "number" ] },
                                "time": { "type": "string", "format": "date-time" }
                            },
                            "required": ["name", "value", "time"]
                        }
                    }
                },
                "required": ["id", "type"]
            }
        }
    },
    "required": ["sensorEventTypes", "behaviorEventTypes", "objectTypes", "sensorEvents", "behaviorEvents", "objects"]
}

=== MariaInesRibeiro98/GameBus-HealthBehaviorMining/schema/extended_OCEL-minimal_sample.json
{
  "sensorEventTypes": [
    {
      "name": "accelerometer",
      "attributes": [
        {
          "name": "x",
          "type": "number"
        },
        {
          "name": "y",
          "type": "number"
        },
        {
          "name": "z",
          "type": "number"
        },
        {
          "name": "activity_id",
          "type": "string"
        }
      ]
    },
    {
      "name": "activity_type",
      "attributes": [
        {
          "name": "type",
          "type": "string"
        },
        {
          "name": "speed",
          "type": "number"
        },
        {
          "name": "steps",
          "type": "number"
        },
        {
          "name": "walks",
          "type": "number"
        },
        {
          "name": "runs",
          "type": "number"
        },
        {
          "name": "freq",
          "type": "number"
        },
        {
          "name": "distance",
          "type": "number"
        },
        {
          "name": "calories",
          "type": "number"
        }
      ]
    },
    {
      "name": "heartrate",
      "attributes": [
        {
          "name": "bpm",
          "type": "number"
        },
        {
          "name": "pp",
          "type": "number"
        }
      ]
    },
    {
      "name": "location",
      "attributes": [
        {
          "name": "latitude",
          "type": "number"
        },
        {
          "name": "longitude",
          "type": "number"
        },
        {
          "name": "altitude",
          "type": "number"
        },
        {
          "name": "speed",
          "type": "number"
        },
        {
          "name": "error",
          "type": "number"
        }
      ]
    }
  ],
  "behaviorEventTypes": [
    {
      "name": "mood",
      "attributes": [
        {
          "name": "valence",
          "type": "number"
        },
        {
          "name": "arousal",
          "type": "number"
        },
        {
          "name": "stress",
          "type": "number"
        }
      ],
      "behaviorEventTypeAttributes": [
        {
          "name": "location",
          "type": "string"
        }
      ]
    },
    {
      "name": "notification",
      "attributes": [
        {
          "name": "action",
          "type": "string"
        }
      ],
      "behaviorEventTypeAttributes": [
        {
          "name": "location",
          "type": "string"
        }
      ]
    },
    {
      "name": "physical_activity_bout",
      "attributes": [
        {
          "name": "lifecycle",
          "type": "string"
        },
        {
          "name": "bout_type",
          "type": "string"
        }
      ],
      "behaviorEventTypeAttributes": [
        {
          "name": "location",
          "type": "string"
        }
      ]
    },
    {
      "name": "location_event",
      "attributes": [
        {
          "name": "lifecycle",
          "type": "string"
        },
        {
          "name": "location_type",
          "type": "string"
        }
      ]
    }
  ],
  "objectTypes": [
    {
      "name": "player",
      "attributes": [
        {
          "name": "id",
          "type": "string"
        }
      ]
    },
    {
      "name": "intervention",
      "attributes": [
        {
          "name": "goal",
          "type": "string"
        },
        {
          "name": "start_date",
          "type": "string"
        },
        {
          "name": "end_date",
          "type": "string"
        }
      ]
    },
    {
      "name": "day",
      "attributes": [
        {
          "name": "date",
          "type": "string"
        },
        {
          "name": "day_of_week",
          "type": "string"
        }
      ]
    },
    {
      "name": "week",
      "attributes": [
        {
          "name": "week_start_date",
          "type": "string"
        },
        {
          "name": "week_number",
          "type": "integer"
        },
        {
          "name": "year",
          "type": "integer"
        }
      ]
    },
    {
      "name": "physical_activity_bout",
      "attributes": [
        {
          "name": "bout_type",
          "type": "string"
        }
      ]
    },
    {
      "name": "notification",
      "attributes": [
        {
          "name": "last_action",
          "type": "string"
        }
      ]
    },
    {
      "name": "stress_self_report",
      "attributes": [
        {
          "name": "stress_value",
          "type": "number"
        }
      ]
    },
    {
      "name": "location_segment",
      "attributes": [
        {
          "name": "location_type",
          "type": "string"
        },
        {
          "name": "start_time",
          "type": "string"
        },
        {
          "name": "end_time",
          "type": "string"
        }
      ]
    }
  ],
  "sensorEvents": [
    {
      "id": "465dd06c-4423-474c-975f-e0413b41b89e",
      "sensorEventType": "accelerometer",
      "time": "2025-05-25T14:00:17.883000",
      "sensorEventTypeAttributes": [
        {
          "name": "x",
          "value": 8.46341323852539
        },
        {
          "name": "y",
          "value": -4.654040336608887
        },
        {
          "name": "z",
          "value": 0.02392822504043579
        }
      ],
      "relationships": [
        {
          "id": "d360ac20-326e-4f6f-8113-baa47ef536ef",
          "type": "object",
          "qualifier": "source"
        },
        {
          "id": "8d47453a-6a5c-454d-806a-971b71a11d8f",
          "type": "object",
          "qualifier": "occurred_on"
        }
      ],
      "event_type": "sensor"
    },
    {
      "id": "318dfae2-58f9-4cd5-b735-9053ca888a84",
      "sensorEventType": "activity_type",
      "time": "2025-05-25T14:02:54.156000",
      "sensorEventTypeAttributes": [
        {
          "name": "type",
          "value": "WALKING"
        },
        {
          "name": "speed",
          "value": 4.099999904632568
        },
        {
          "name": "steps",
          "value": 1707
        },
        {
          "name": "walks",
          "value": 1693
        },
        {
          "name": "runs",
          "value": 3
        },
        {
          "name": "freq",
          "value": 1.600000023841858
        },
        {
          "name": "distance",
          "value": 1254.780029296875
        },
        {
          "name": "calories",
          "value": 61.86999893188477
        }
      ],
      "relationships": [
        {
          "id": "d360ac20-326e-4f6f-8113-baa47ef536ef",
          "type": "object",
          "qualifier": "source"
        },
        {
          "id": "8d47453a-6a5c-454d-806a-971b71a11d8f",
          "type": "object",
          "qualifier": "occurred_on"
        }
      ],
      "event_type": "sensor"
    },
    {
      "id": "e4f2ea1a-fa01-4fba-a0f9-8e033044428a",
      "sensorEventType": "heartrate",
      "time": "2025-05-25T14:00:17.881000",
      "sensorEventTypeAttributes": [
        {
          "name": "bpm",
          "value": 90.0
        },
        {
          "name": "pp",
          "value": 767.0
        }
      ],
      "relationships": [
        {
          "id": "d360ac20-326e-4f6f-8113-baa47ef536ef",
          "type": "object",
          "qualifier": "source"
        },
        {
          "id": "8d47453a-6a5c-454d-806a-971b71a11d8f",
          "type": "object",
          "qualifier": "occurred_on"
        }
      ],
      "event_type": "sensor"
    },
    {
      "id": "109085bf-9c19-4c2a-8792-1bfaba12b242",
      "sensorEventType": "location",
      "time": "2025-05-25T14:02:22",
      "sensorEventTypeAttributes": [
        {
          "name": "latitude",
          "value": 52.09357452392578
        },
        {
          "name": "longitude",
          "value": 5.111295223236084
        },
        {
          "name": "altitude",
          "value": 46.5
        },
        {
          "name": "speed",
          "value": 5.576400089263916
        },
        {
          "name": "error",
          "value": 11.0
        }
      ],
      "relationships": [
        {
          "id": "d360ac20-326e-4f6f-8113-baa47ef536ef",
          "type": "object",
          "qualifier": "source"
        },
        {
          "id": "8d47453a-6a5c-454d-806a-971b71a11d8f",
          "type": "object",
          "qualifier": "occurred_on"
        }
      ],
      "event_type": "sensor"
    }
  ],
  "behaviorEvents": [
    {
      "id": "67b8d80e-fb50-4037-9c3a-8db93746fc89",
      "behaviorEventType": "mood",
      "time": "2025-05-25T13:00:00.886000",
      "behaviorEventTypeAttributes": [
        {
          "name": "valence",
          "value": 6
        },
        {
          "name": "arousal",
          "value": 6
        },
        {
          "name": "stress",
          "value": 4
        },
        {
          "name": "location",
          "value": "invalid"
        }
      ],
      "relationships": [
        {
          "id": "d360ac20-326e-4f6f-8113-baa47ef536ef",
          "type": "object",
          "qualifier": "source"
        },
        {
          "id": "8d47453a-6a5c-454d-806a-971b71a11d8f",
          "type": "object",
          "qualifier": "occurred_on"
        },
        {
          "id": "b007b627-8e70-4a80-b511-be98b3e2bf3a",
          "type": "object",
          "qualifier": "reports_stress"
        },
        {
          "type": "object",
          "id": "38643450-f107-48a1-bd35-4dbdbfdc7a1d",
          "qualifier": "occurred_in_location"
        },
        {
          "id": "a61d3d86-ba05-4fe9-86f1-737f11f1bea4",
          "type": "object",
          "qualifier": "notified_by"
        }
      ],
      "event_type": "behavior"
    },
    {
      "id": "b75e0192-027a-452e-bc60-661d42c68d79",
      "behaviorEventType": "notification",
      "time": "2025-05-25T12:59:53.042000",
      "behaviorEventTypeAttributes": [
        {
          "name": "action",
          "value": "READ"
        },
        {
